/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modern_tutions;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static modern_tutions.StudentTable.StudentTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User
 */
public class Student_form extends javax.swing.JFrame {

    /**
     * Creates new form Student_form
     */
    private static Connection myConnectObj=null;
    private static Statement myStatObj=null;
    private static ResultSet myResObj=null;
     
    public Student_form() {
        initComponents();
        selectionall();
        setTitle("Student Form");
    }
    private void selectionall(){
        
        try{
            myConnectObj=DriverManager.getConnection("jdbc:derby://localhost:1527/PaymentDatabase","Include101","Include101");
            myStatObj=myConnectObj.createStatement();
            myResObj=myStatObj.executeQuery("SELECT * FROM INCLUDE101.LOGINDATABASE");
            myResObj=myStatObj.executeQuery("SELECT * FROM INCLUDE101.STUDENTTABLE");
        }
        
       catch(SQLException e )
       {
           e.printStackTrace();
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        University_preference = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        Subject_preference = new javax.swing.JLabel();
        Payment_range = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        Email_no = new javax.swing.JLabel();
        Contact_no = new javax.swing.JLabel();
        Class = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        User_name = new javax.swing.JLabel();
        Student_name = new javax.swing.JLabel();
        Subject_Preference = new javax.swing.JTextField();
        jTextField_payment_range = new javax.swing.JTextField();
        jTextField_address = new javax.swing.JTextField();
        jTextField_email_no = new javax.swing.JTextField();
        jTextField_contact_no = new javax.swing.JTextField();
        jSpinner_class = new javax.swing.JSpinner();
        jPasswordField_password = new javax.swing.JPasswordField();
        jTextField_user_name = new javax.swing.JTextField();
        jTextField_student_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_universty_prefernce = new javax.swing.JComboBox<>();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        University_preference.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        University_preference.setText("University Preference");
        jPanel2.add(University_preference);
        University_preference.setBounds(60, 600, 270, 29);

        Back.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modern_tutions/backBUtton.png"))); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel2.add(Back);
        Back.setBounds(910, 600, 120, 40);

        Submit.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modern_tutions/Submit.png"))); // NOI18N
        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel2.add(Submit);
        Submit.setBounds(750, 600, 150, 40);

        Subject_preference.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Subject_preference.setText("Subject Preference");
        jPanel2.add(Subject_preference);
        Subject_preference.setBounds(90, 550, 240, 29);

        Payment_range.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Payment_range.setText("Payment Range");
        jPanel2.add(Payment_range);
        Payment_range.setBounds(120, 480, 200, 29);

        Address.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Address.setText("Address");
        jPanel2.add(Address);
        Address.setBounds(210, 420, 100, 29);

        Email_no.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Email_no.setText("Email Address");
        jPanel2.add(Email_no);
        Email_no.setBounds(150, 360, 180, 29);

        Contact_no.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Contact_no.setText("Contact No");
        jPanel2.add(Contact_no);
        Contact_no.setBounds(180, 300, 140, 29);

        Class.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Class.setText("Class");
        jPanel2.add(Class);
        Class.setBounds(250, 260, 80, 29);

        Password.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Password.setText("Password");
        jPanel2.add(Password);
        Password.setBounds(200, 210, 120, 29);

        User_name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        User_name.setText("User Name");
        jPanel2.add(User_name);
        User_name.setBounds(180, 150, 131, 29);

        Student_name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Student_name.setText("Student Name");
        jPanel2.add(Student_name);
        Student_name.setBounds(140, 90, 180, 20);

        Subject_Preference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subject_PreferenceActionPerformed(evt);
            }
        });
        jPanel2.add(Subject_Preference);
        Subject_Preference.setBounds(340, 540, 330, 40);
        jPanel2.add(jTextField_payment_range);
        jTextField_payment_range.setBounds(340, 480, 330, 40);
        jPanel2.add(jTextField_address);
        jTextField_address.setBounds(340, 420, 330, 40);
        jPanel2.add(jTextField_email_no);
        jTextField_email_no.setBounds(340, 360, 330, 40);

        jTextField_contact_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_contact_noActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_contact_no);
        jTextField_contact_no.setBounds(340, 300, 330, 40);
        jPanel2.add(jSpinner_class);
        jSpinner_class.setBounds(340, 260, 60, 30);

        jPasswordField_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_passwordMouseClicked(evt);
            }
        });
        jPasswordField_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_passwordActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordField_password);
        jPasswordField_password.setBounds(340, 200, 190, 40);
        jPanel2.add(jTextField_user_name);
        jTextField_user_name.setBounds(340, 140, 330, 40);

        jTextField_student_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_student_nameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_student_name);
        jTextField_student_name.setBounds(340, 80, 330, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Please fill up the Student Form: ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 0, 390, 90);

        jTextField_universty_prefernce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aust", "Du", "Buet", "Ruet","cuet","Sust","Public","Private","Any" }));
        jPanel2.add(jTextField_universty_prefernce);
        jTextField_universty_prefernce.setBounds(340, 610, 330, 26);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modern_tutions/depositphotos_42642647-stock-photo-light-purple-background-texture.jpg"))); // NOI18N
        jPanel2.add(image);
        image.setBounds(0, 0, 1080, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private static boolean validate(String password) {
  // Check for null, then a length less then 6 
  // > 10 check.
        if (password == null || password.length() < 6 || password.length() > 10) {
            return false;
        }
        boolean containsChar = false;
        boolean containsDigit = false;

        for (char c : password.toCharArray()) {
            if (Character.isLetter(c)) {
                containsChar = true;
            } 
            else if (Character.isDigit(c)) {
                containsDigit = true;
            }
            if (containsChar && containsDigit) {
                return true;
            }
            if (password.contains(" ")) {
                return false;
            }

        }
        return false;
    }
    private void jTextField_student_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_student_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_student_nameActionPerformed

    private void jTextField_contact_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_contact_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_contact_noActionPerformed

    private void Subject_PreferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subject_PreferenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Subject_PreferenceActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Login_Page object=new Login_Page();
        object.show();
        this.setVisible(false);
                
    }//GEN-LAST:event_BackActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        

        // TODO add your handling code here:
        String Password_v = new String (jPasswordField_password.getPassword());
        if(validate(Password_v) == true)
        {
            Teacher_table object = new Teacher_table();
            object.show();
            this.setVisible(false);
        }
        else
        {
            String msg = "Invalid Password please enter again";
            JOptionPane.showMessageDialog(this, msg);
        }
        
       
        
        try{
            String UsernameStudent = jTextField_user_name.getText(); 
            char[] PasswordStudent = jPasswordField_password.getPassword();
            PreparedStatement add = myConnectObj.prepareStatement("Insert into Include101.LOGINDATABASE values (?,?)");
            add.setString(1, UsernameStudent);
            add.setString(2, String.valueOf(PasswordStudent));
            int row = add.executeUpdate();
            
        }
        catch(SQLException e){
            e.printStackTrace();
            
        }
         
         try{
            String StudentName = jTextField_student_name.getText();
            Integer cls=(Integer)jSpinner_class.getValue();
            String ContactNo=jTextField_contact_no.getText();
            String EmailAddress=jTextField_email_no.getText();
            String Address1=jTextField_address.getText();
            String PaymentRange=jTextField_payment_range.getText();
            String SubjectPrefernce=Subject_Preference.getText();
            String UniversityPreference=(String) jTextField_universty_prefernce.getSelectedItem();
            PreparedStatement add = myConnectObj.prepareStatement("Insert into Include101.STUDENTTABLE values (?,?,?,?,?,?,?,?)");
            add.setString(1, StudentName);
            add.setInt(2, cls);
            add.setString(4, ContactNo);
            add.setString(5, EmailAddress);
            add.setString(6, Address1);
            add.setString(7, PaymentRange);
            add.setString(3, SubjectPrefernce);
            add.setString(8, UniversityPreference);
            
            int row2 = add.executeUpdate();
            
        }
        catch(SQLException e){
            e.printStackTrace();
            
        }
        
        selectionall();
                                             

        
    }//GEN-LAST:event_SubmitActionPerformed

    private void jPasswordField_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_passwordActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPasswordField_passwordActionPerformed

    private void jPasswordField_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_passwordMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Please enter your password.\n"+ "Your password must have 6-10 characters\n" + "Your password must contain at least one letter and one digit without any space");
    }//GEN-LAST:event_jPasswordField_passwordMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JButton Back;
    private javax.swing.JLabel Class;
    private javax.swing.JLabel Contact_no;
    private javax.swing.JLabel Email_no;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Payment_range;
    private javax.swing.JLabel Student_name;
    private javax.swing.JTextField Subject_Preference;
    private javax.swing.JLabel Subject_preference;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel University_preference;
    private javax.swing.JLabel User_name;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JSpinner jSpinner_class;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_contact_no;
    private javax.swing.JTextField jTextField_email_no;
    private javax.swing.JTextField jTextField_payment_range;
    private javax.swing.JTextField jTextField_student_name;
    private javax.swing.JComboBox<String> jTextField_universty_prefernce;
    private javax.swing.JTextField jTextField_user_name;
    // End of variables declaration//GEN-END:variables
}
